# NumPy
NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.

## Introducing NumPy Arrays

In [7]:
import numpy as np

### Some Terms in NumPy

- In NumPy, each dimension is called an axis.
- The number of axes is called the rank.
    - For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    - The first axis has length 3, the second has length 4.
- An array's list of axis lengths is called the shape of the array.
    - For example, the above matrix's shape is (3, 4).
    - The rank is equal to the shape's length.
- The size of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)


### Simple Array Creation

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

### Checking the type

In [4]:
type(a)

numpy.ndarray

### Numeric "Type" of elements

In [5]:
a.dtype

dtype('int32')

### Number of dimensions

In [6]:
a.ndim

1

### Array Shape
Shape returns a tuple and listing the length of the array along each dimension

In [8]:
a.shape

(4,)

### Bytes per element

In [9]:
a.itemsize

4

### Bytes of memory used
Return the number of bytes used by the data portion of the array

In [10]:
a.nbytes

16

## Array Operations

### Simple Array math

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a + b

array([3, 5, 7, 9])

In [12]:
a * b

array([ 2,  6, 12, 20])

In [13]:
a ** b

array([   1,    8,   81, 1024], dtype=int32)

### MATH functions

- NumPy defines these constants: 
    - pi = 3.1415926
    - e = 2.71828

In [16]:
# Create array from 0. to 10.

x = np.arange(11.)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
# Multiply entire array by scalar value

c = (2*np.pi) / 10
c

0.6283185307179586

In [18]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [19]:
# in-place operations
x *= c
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [22]:
# apply functions to array
y = np.sin(x)
y

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

## Setting Array Elements

### Array Indexing

In [25]:
a[0]

1

In [26]:
a[0] = 10
a

array([10,  2,  3,  4])

### Beware of type coercion 

In [27]:
a.dtype

dtype('int32')

In [29]:
# assigning a float into an int32 array truncates the decimal part
a[0] = 100.6
a

array([100,   2,   3,   4])

In [30]:
# fill has the same behavior
a.fill(-4.8)
a

array([-4, -4, -4, -4])

## Multi-Dimensional Arrays

In [31]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

### Shape = (Rows, Columns) 

In [32]:
a.shape

(2, 4)

### Element Count

In [33]:
a.size

8

### Number of Dimensions

In [34]:
a.ndim

2

### Get/Set Elements

In [35]:
a[1,3]

13

In [36]:
a[1,3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

### Address second row using single index 

In [37]:
a[1]

array([10, 11, 12, -1])

## Indexing and Slicing

var[lower:upper:step]  
Extracts a portion of a sequence by specifying the lower and upper bound.  
The lower bound element is included, but the upper-bound element is not included.  
Mathematically: [lower, upper). The step value specifies the strides between elements.  

In [39]:
#indices      0  1  2  3  4
#            -5 -4 -3 -2 -1       
a = np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [40]:
a[1:3]

array([11, 12])

In [41]:
# negative indices work also
# Ignores the first element and the last two element
a[1:-2]

array([11, 12])

In [42]:
# It breaks my mind to think about the logic
a[-4:3]

array([11, 12])

### Omitting indcies
Omitting boundaries are assumed to be the beginning (or end) of the list

In [43]:
# grab first three elements
a[:3]

array([10, 11, 12])

In [45]:
# grab last two elements
a[-2:]

array([13, 14])

In [46]:
# every other element
a[::2]

array([10, 12, 14])

## Array Slicing 

### Slicing works much like standard python slicing 

In [48]:
a = np.array([[0, 1, 2, 3, 4, 5],
              [10, 11, 12, 13, 14,15],
              [20, 21, 22, 23, 24, 25],
              [30, 31, 32, 33, 34, 35],
              [40, 41, 42, 43, 44, 45],
              [50, 51, 52, 53, 54, 55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [49]:
a[0, 3:5]

array([3, 4])

In [50]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [51]:
a[:, 2]

array([ 2, 12, 22, 32, 42, 52])

### Strided are also possible 

In [52]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Slices are references

Slices are references to locations in memory.  
These memory locations can be used in assignment operations

In [54]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [56]:
# Slicing the last two elements returns the data there
a[-2:]

array([3, 4])

In [58]:
# we can insert an iterable of length two
a[-2:] = [-1, -2]
a

array([ 0,  1,  2, -1, -2])

In [59]:
# or a scalar value
a[-2:] = 100
a

array([  0,   1,   2, 100, 100])

## Slice Arrays share data

Arrays created by slicing share data with the originating array.  
Changing values in a slice also changes the original array.

In [60]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [62]:
# create a slice containing two elements of a
b = a[2:4]
b

array([2, 3])

In [64]:
b[0] = 10
# changing b changed a !
a

array([ 0,  1, 10,  3,  4])

In [67]:
b = a.copy()
b

array([ 0,  1, 10,  3,  4])

In [68]:
# after copying the array a to array b, changing b wont change a
b[0] = 100
print("b array is : {}".format(b))
print("a array is : {}".format(a))

b array is : [100   1  10   3   4]
a array is : [ 0  1 10  3  4]


## How array works in python 

In [91]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [92]:
# Get an item
print(a[0])
print(a.__getitem__(0))

0
0


In [93]:
# Set an item
a[0] = 100
print(a)
a.__setitem__(1, 150)
print(a)

[100   1   2   3   4]
[100 150   2   3   4]


### This is how python get/set an item in array, dictionary pandas, numpy 

Double underscore methods in python is called as "dunder" or magic methods.  
Other examples are as follows.  
\__init__, \__add__, \__len__, \__repr__

## Fancy Indexing  

### Indexing by position 

In [94]:
a = np.arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [95]:
# fancy indexing
indices = [1, 2, -3]
y = a[indices]
y

array([10, 20, 50])

In [96]:
# This also works with setting
a[indices] = 99
a

array([ 0, 99, 99, 30, 40, 99, 60, 70])

### Indexing with booleans 

In [97]:
# manual creation of masks
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)

# fancy indexing
y = a[mask]
print(y)

[99 99 99]


In [102]:
# creation of masks using condition
b = np.array([-1, -3, 1, 4, -6, 9, 3])
negative_mask = b < 0
print(b[negative_mask])

# set the negative elements is equal to zero
b[negative_mask] = 0
print(b)

[-1 -3 -6]
[0 0 1 4 0 9 3]


## Fancy Indexing in 2D 

Unlike slicing, fancy indexing creates copies instead of a view into original array.

In [103]:
a = np.array([[0, 1, 2, 3, 4, 5],
              [10, 11, 12, 13, 14,15],
              [20, 21, 22, 23, 24, 25],
              [30, 31, 32, 33, 34, 35],
              [40, 41, 42, 43, 44, 45],
              [50, 51, 52, 53, 54, 55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [104]:
a[[0, 1, 2, 3, 4],
  [1, 2, 3, 4, 5]]

array([ 1, 12, 23, 34, 45])

In [105]:
a[3:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [106]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

In [108]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
# Extract all the numbers divisible by 3 using a boolean mask
a[a%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

# Array constructor Examples

### Floating point arrays 

In [3]:
import numpy as np
a = np.array([0, 1.0, 2, 3])
print(a.dtype)
print(a.nbytes)

float64
32


### Reducing Precision

In [4]:
a = np.array([0, 1., 2, 3], dtype='float32')
print(a.dtype)
print(a.nbytes)

float32
16


### Unsigned Integer Byte 

In [6]:
a = np.array([0, 1, 2, 3], dtype='uint8')
print(a.dtype)
print(a.nbytes)

uint8
4


### ARANGE 
arange([start,stop, step], dtype=None)  
Nearly identical to Python's range ().  
Creates an array of values in the range [start, stop) with the specified step value.  
Allows non-integer values for start, stop and step.  
Default dtype is derived from the start, stop and step values.

In [7]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(0, 2*(np.pi), np.pi/4)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

In [12]:
np.arange(1.5, 2.1,0.3)

array([1.5, 1.8, 2.1])

### Ones, Zeros
ones(shape, dtype='float64')
zeros(shape, dtype='float64')

shape is a number or sequence specifying the dimensions of the array. If the dtype is not specified, it defaults to float64.

In [13]:
np.ones((2,3), dtype='float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [14]:
np.zeros(3)

array([0., 0., 0.])

### Identity 
Generate an n by n identity array. The default type is float64.

In [15]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
a.dtype

dtype('float64')

In [17]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Empty and fill 
empty(shape, dtype=float64, order='C')

In [18]:
np.empty(2)

array([5.43230922e-312, 7.29112202e-304])

In [19]:
# array filled with 5.0
a = np.full(2, 5.0)
a

array([5., 5.])

In [20]:
# alternative approaches but slower
a = np.empty(2)
a.fill(4.0)
a

array([4., 4.])

In [21]:
a[:] = 3.0
a

array([3., 3.])

### Linspace

Generate N evenly spaced elements between (and including) start and stop values

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Logspace
Generate N evenly spaced elements on a log scale between base\**start and base\**stop (default base = 10)

In [23]:
np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

### Array from/to txt files

In [25]:
# loadtxt() automatically generates an array from the text file
#arr = np.loadtxt('data.txt', skiprows=1, dtype=int, delimiter=",", usecols = (0, 1, 2, 4), comments = "%")

# save an array into a text file
#np.savetxt('filename', arr)