# NumPy
NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.

## Introducing NumPy Arrays

In [7]:
import numpy as np

### Some Terms in NumPy

- In NumPy, each dimension is called an axis.
- The number of axes is called the rank.
    - For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    - The first axis has length 3, the second has length 4.
- An array's list of axis lengths is called the shape of the array.
    - For example, the above matrix's shape is (3, 4).
    - The rank is equal to the shape's length.
- The size of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)


### Simple Array Creation

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

### Checking the type

In [4]:
type(a)

numpy.ndarray

### Numeric "Type" of elements

In [5]:
a.dtype

dtype('int32')

### Number of dimensions

In [6]:
a.ndim

1

### Array Shape
Shape returns a tuple and listing the length of the array along each dimension

In [8]:
a.shape

(4,)

### Bytes per element

In [9]:
a.itemsize

4

### Bytes of memory used
Return the number of bytes used by the data portion of the array

In [10]:
a.nbytes

16

## Array Operations

### Simple Array math

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a + b

array([3, 5, 7, 9])

In [12]:
a * b

array([ 2,  6, 12, 20])

In [13]:
a ** b

array([   1,    8,   81, 1024], dtype=int32)

### MATH functions

- NumPy defines these constants: 
    - pi = 3.1415926
    - e = 2.71828

In [16]:
# Create array from 0. to 10.

x = np.arange(11.)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
# Multiply entire array by scalar value

c = (2*np.pi) / 10
c

0.6283185307179586

In [18]:
c * x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [19]:
# in-place operations
x *= c
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [22]:
# apply functions to array
y = np.sin(x)
y

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

## Setting Array Elements

### Array Indexing

In [25]:
a[0]

1

In [26]:
a[0] = 10
a

array([10,  2,  3,  4])

### Beware of type coercion 

In [27]:
a.dtype

dtype('int32')

In [29]:
# assigning a float into an int32 array truncates the decimal part
a[0] = 100.6
a

array([100,   2,   3,   4])

In [30]:
# fill has the same behavior
a.fill(-4.8)
a

array([-4, -4, -4, -4])

## Multi-Dimensional Arrays

In [31]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

### Shape = (Rows, Columns) 

In [32]:
a.shape

(2, 4)

### Element Count

In [33]:
a.size

8

### Number of Dimensions

In [34]:
a.ndim

2

### Get/Set Elements

In [35]:
a[1,3]

13

In [36]:
a[1,3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

### Address second row using single index 

In [37]:
a[1]

array([10, 11, 12, -1])